### ISSUE TITLE
Spatial partitioning messaging Not guaranteeing the desired results (or not?)

### ISSUE THREAD

**Issue by jiruhameru** [FLAMEGPU/FLAMEGPU#238]
Based on the Boids partitioning model, I created similar model whereby continuous agents navigate and exchange messages in a 3D space using 'spatial partitioning scheme'. In the model, agents possess an interaction radius, and are supposed to steer towards the centre of mass of their neighbors, but when I run the simulation with only 10 or even 02 agents, they do not get closer.. could you enlighten me on this issue? Does the partitioning type have some effect? Will I get different output if I adopt brute-force partitioning for example? (for testing purpose only)

Thanks in advance.

**Comment by ptheywood** [comment]
The spatially partitioned messaging configuration effects the number of messages which agents will parse, and this value is independent of an interaction radius specified in functions.c (although in practice you probably want them to be the same). 

Using spatial partitioning rather than brute force messaging each agent will have to iterate the full list of messages, rather than only those within the radius specified by the spatial partitioning configuration (in the XMLModelFile.XML). If the interaction radius you use in the agent function is greater than that specified in the XMLModelFile then you would see different behaviour using brute force messaging. 
If the spatial partitioning radius is greater than or equal to agent function interaction radius then behaviour would be the same. 

In addition, spatially partitioned messages wrap in the X and Y dimensions to form a torus.

It is hard to say why your agents are not moving towards each other with the limited information available.

**Comment by mondus** [comment]
@jiruhameru Does this clarify things for you? Do you need any more information?

**Comment by jiruhameru** [comment]
@mondus  Yes it does, thanks a lot.
