### ISSUE TITLE
XMLModelFile.xml with scientific notation not valid in SHARC

### ISSUE THREAD

**Issue by cmoralesmx** [FLAMEGPU/FLAMEGPU#260]
After seeing #256, I decided to try scientific notation to specify the default value for some agent variables.  
However, doing so produces validation errors in `XMLModelFile.xml` when trying to compile in SHARC (I have not tried this in a local linux machine).  

Although, I also attempted with other formats such as capital E instead of non-capital and using numbers with less decimals, I do not see support for scientific notation in the regular expression used for checking the element  
![image](https://user-images.githubusercontent.com/1790200/59922911-dafb8f00-9429-11e9-9bb6-2ee1d801befc.png)

Therefore, I would like to ask if this type of notation is supported and what is the canonical form to use it?  

For reference, the code producing such errors is available [here](https://github.com/cmoralesmx/ev_diffusion/blob/48176acc22323da74a4aa3b0e1a4bdcaa01d10a5/examples/ExtracellularVesiclesDiffusion/src/model/XMLModelFile.xml), more specifically at lines [22-27](https://github.com/cmoralesmx/ev_diffusion/blob/48176acc22323da74a4aa3b0e1a4bdcaa01d10a5/examples/ExtracellularVesiclesDiffusion/src/model/XMLModelFile.xml#L22-L27), [34-39](https://github.com/cmoralesmx/ev_diffusion/blob/48176acc22323da74a4aa3b0e1a4bdcaa01d10a5/examples/ExtracellularVesiclesDiffusion/src/model/XMLModelFile.xml#L34-L39), and [67-72](https://github.com/cmoralesmx/ev_diffusion/blob/48176acc22323da74a4aa3b0e1a4bdcaa01d10a5/examples/ExtracellularVesiclesDiffusion/src/model/XMLModelFile.xml#L67-L72).

**Comment by ptheywood** [comment]
It looks like I overlooked scientific notation when improving the use of `defaultValue`. 

The regular expression used for validating the scheme needs changing to support this. 

For now, the simple fix is to disable the validation of your XMLModelFile.
The simplest (untested) way to do this would be to modify `tools/common.mk` [Line 319 (in current master](https://github.com/FLAMEGPU/FLAMEGPU/blob/master/tools/common.mk#L319)) replacing 
```
validate: makedirs $(LAST_VALID_AT)
```
with 
```
validate: makedirs
```

This *should*  stop the validation from occurring allowing your model to build and run (assuming gcc is happy with the floats specified)

I'll post again once I've fixed the issue.

**Comment by ptheywood** [comment]
I've fixed this by updating the regular expression in `FLAMEGPU/schemas/XMML.xsd` which validates the form of defaultValues, in commit 510f749 (PR #261)

This now accepts any C valid decimal, with support for comma separated values when using vector types.

I've tested this with your XMLModelFile from cmoralesmx/ev_diffusion@48176acc22323da74a4aa3b0e1a4bdcaa01d10a5.

To make these changes permanent, update the `FLAMEGPU/schemas/XMML.xsd` file in your repository, either:

+ Manaully
+ Or pull in the latest changes through the FLAMEGPU/FLAMEGPU repo, which may include other fixes since you created your repository. From a quick look at your repo, the commands to do this could be the following: Note that this only applies to the current state of your repo, where you have not made any changes in the master branch.
    ```
    # Switch to your master branch
    git checkout master
    # Add the upstream repository (if not already a remote)
    git remote add upstream git@github.com:FLAMEGPU/FLAMEGPU.git
    # Ensure you have the latest information on the upstream repository
    git fetch upstream
    # Update your master branch to match the upstream master branch (or rebase) 
    git reset --hard upstream/master
    # Switch back to your branch
    git checkout ev_diffusion
    # finally rebase the changes in master onto your branch.
    git rebase master
    ```
