### ISSUE TITLE
Add a new agent type to the custom visualisation

### ISSUE THREAD

**Issue by WYyyyaaa** [FLAMEGPU/FLAMEGPU#300]
I added another type of agent similar to the NavMap agent in the example PedestrainNavigation (using Custom Visualisation). I want them to be displayed in the visual window and be able to update location information (altitude changes). Do I need to manually write the .cpp .cu and .h files belonging to it? This seems a bit complicated. In order to show the new agents, what content should I add to the existing file? Thanks!

**Comment by ptheywood** [comment]
Yes you will have to write your own code to render your new agents in the custom visualisation, which is unfortunately non trivial. 

Essentially you will want to duplicate and modify the contents of `NavMapPopulation.h`, `NavMapPopulation.cpp` and `NavMapPopulation.cu` although you will not need all of the functions. 

As a minimum, you will need to implement your own versions of the following (but renamed to avoid name clashes), and adjust to reference your population of agents rather than NavMap agents.

+ `initNavMapPopulation`
+ `renderNavMapPopulation`
+ `generate_instances`
+ `navmap_vshader_source`

You will also need to modify `CustomVisualisation.cpp` to include your new header file, and call your `init*Population` and `render*Population` methods at the same times as the existing navmap calls within the `initVisualisation` and `display` methods respectively.

**Comment by WYyyyaaa** [comment]
It's helpful! Thx!
